### ISSUE TITLE
Installing on Mac is failing

### ISSUE THREAD

**Issue by lakstap** [firehol/netdata#1915]
acos_sysctl.c
macos_sysctl.c:117:10: fatal error: 'netinet6/scope6_var.h' file not found
#include <netinet6/scope6_var.h>
         ^

**Comment by GitStoph** [comment]
I just installed successfully with Sierra 10.12.3 less than a week ago. Was able to update just now without issue as well.

**Comment by ktsaou** [comment]
@vlvkobal any ideas? Some system headers are missing, but I don't know how to install them...

**Comment by octomike** [comment]
Confirmed failing install with 10.10.5 (yosemite). Even after pulling scope6_var.h from elsehwere (long shot anyway) building fails with:

```bash
macos_sysctl.c:458:92: error: no member named 'tcps_ecn_recv_ce' in 'struct tcpstat'
            if (do_ecn == CONFIG_BOOLEAN_YES || (do_ecn == CONFIG_BOOLEAN_AUTO && (tcpstat.tcps_ecn_recv_ce || tcpstat.tcps_ecn_not_supported))) {
                                                                                   ~~~~~~~ ^
macos_sysctl.c:458:120: error: no member named 'tcps_ecn_not_supported' in 'struct tcpstat'
            if (do_ecn == CONFIG_BOOLEAN_YES || (do_ecn == CONFIG_BOOLEAN_AUTO && (tcpstat.tcps_ecn_recv_ce || tcpstat.tcps_ecn_not_supported))) {
                                                                                                               ~~~~~~~ ^
macos_sysctl.c:471:52: error: no member named 'tcps_ecn_recv_ce' in 'struct tcpstat'
                rrddim_set(st, "InCEPkts", tcpstat.tcps_ecn_recv_ce);
                                           ~~~~~~~ ^
macos_sysctl.c:472:55: error: no member named 'tcps_ecn_not_supported' in 'struct tcpstat'
                rrddim_set(st, "InNoECTPkts", tcpstat.tcps_ecn_not_supported);

```

A quick search revels that the member was introduced in XNU somewehre between 2782.x and 3247.x (10.11). I will test building on a patched 10.11 machine and report.

**Comment by octomike** [comment]
It builds on 10.11, but now I get #2028

**Comment by ktsaou** [comment]
Cleaning up. I am closing this.
If you still need help, post here.
Let's discuss the mutex issue on #2028

**Comment by komradebob** [comment]
Still failing on 10.10.5

**Comment by ktsaou** [comment]
Could you please post the error?

**Comment by ktsaou** [comment]
@vlvkobal have a look at this please.

**Comment by snigel** [comment]
Tried to install on osx 10.5 (yes, ancient), same error here.

**Comment by ktsaou** [comment]
@vlvkobal we really need your skills here...

**Comment by GitStoph** [comment]
@snigel If it'd help, I could post my steps for installing on 10.11-10.13? I've been able to make it work on the more recent macOS versions.

**Comment by vlvkobal** [comment]
@ktsaou unfortunately I can't help. I don't have access to macOS anymore. I think it would be easier to disable the controversial code for ipv6 charts for older macOS versions. But even if I found time to do it, I couldn't test the code. Anyway, let see what @GitStoph did to make it work. It might be easier solution.

**Comment by simonnagl** [comment]
I could also help testing code on macOS (only 10.12.x). If I can help just mention.

**Comment by GitStoph** [comment]
`sudo xcode-select --install` and accept the agreement
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` - note, dont run as root.
`brew install ossp-uuid autoconf automake pkg-config coreutils bash`
`sudo nano /etc/shells`
	- add /usr/local/bin/bash
`chsh -s /usr/local/bin/bash`
`sudo chsh -s /usr/local/bin/bash`
`git clone https://github.com/firehol/netdata.git`
`cd netdata`
`sudo ./netdata-installer.sh --install ~/opt` - note, USE sudo here.
`sudo nano ~/opt/netdata/etc/netdata/netdata.conf`
	- verify set to run as root (yes, i have my netdata run as root since it's a slave to a master, and it fixes several plugins that have permission issues)
		- [plugins]
			○ uncomment plugins path environment variable
			○ add: `:/usr/local/bin/bash:/usr/local/opt/coreutils/libexec/gnubin`

This is pieced together from some documentation I had made a bit back. I dont think I missed anything in here, but feel free to holler if you have a problem!

**Comment by ktsaou** [comment]
vagrant boxes have macos versions for virtualbox: https://app.vagrantup.com/boxes/search?page=1&provider=&q=macos&sort=downloads&utf8=%E2%9C%93

Running one now:

![screenshot from 2017-09-29 21-48-42](https://user-images.githubusercontent.com/2662304/31031784-65652f60-a562-11e7-9137-6f4542ac15d2.png)

interesting...

Unfortunately the older one is macos 10.11

**Comment by ktsaou** [comment]
Searching for `osx` reveals older versions, even 10.7 https://app.vagrantup.com/boxes/search?page=1&provider=&q=osx&sort=downloads&utf8=%E2%9C%93

**Comment by snigel** [comment]
I do have the directory /usr/include/netinet6 but it does not include scope6_var.h

@GitStoph 
>sudo xcode-select --install
I had Xcode installed since before.

> brew install ossp-uuid autoconf automake pkg-config coreutils bash
Everything except coreutils was installed since before.
Trying to compile after installation of coreutils gives:
macos_sysctl.c:117:10: fatal error: netinet6/scope6_var.h: No such file or directory

I'm running ancient bash as default, let's switch.
I add /opt/local/bin/bash to /etc/shells
```
chsh -s /usr/local/bin/bash
sudo chsh -s /usr/local/bin/bash
```
Trying to recompile using bash 4.4 gives:
macos_sysctl.c:117:10: fatal error: netinet6/scope6_var.h: No such file or directory

**Comment by octomike** [comment]
As I menioned earlier in this issue, it seems that ECN stats are not supported prior to OSX 10.11. At least the [struct from that time](https://github.com/apple/darwin-xnu/blob/0e29ffdbf498553825b6d277da236636c8295163/bsd/netinet/tcp_var.h#L927) is missing some members

I made it compile with the mentioned yosemite vagrant box by inlining the relevant `scope6_var.h` part, similar to the ip6stat struct in `macos_sysctl.c` and using the `__MAC_OS_X_VERSION_MIN_REQUIRED` macro as defined in [Availability.h](https://github.com/apple/darwin-xnu/blob/5394bb038891708cd4ba748da79b90a33b19f82e/EXTERNAL_HEADERS/Availability.h) to skip the ecn part.

If these hoops are desired, I can try to make a PR, but I'm not sure if the project maintainers want to introduce backwards compatibility of this kind at all. I mean, Yosemite has been semi-officially deprecated earlier this week with the release of macOS 10.13 anyway.

**Comment by ktsaou** [comment]
If you can do it in a way that it will not affect users with newer versions, please make a PR...

**Comment by ktsaou** [comment]
merged the fix to support building netdata on OSX 10.9+
Thank you @octomike !

**Comment by snigel** [comment]
Still failing for me, but then again, I'm on an ancient OS, 10.5.

```
macos_sysctl.c: In function 'do_macos_sysctl':
macos_sysctl.c:541:78: error: 'struct udpstat' has no member named 'udps_nosum'; did you mean 'udps_badsum'?
                 rrddim_set(st, "InCsumErrors", udpstat.udps_badsum + udpstat.udps_nosum);
                                                                              ^~~~~~~~~~
                                                                              udps_badsum
macos_sysctl.c:542:56: error: 'struct udpstat' has no member named 'udps_filtermcast'; did you mean 'udps_noportbcast'?
                 rrddim_set(st, "IgnoredMulti", udpstat.udps_filtermcast);
                                                        ^~~~~~~~~~~~~~~~
                                                        udps_noportbcast
```

**Comment by ktsaou** [comment]
merged it!
